### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by dave-lew99** [linode/packer-builder-linode#10]
Hi,

I may be using this project incorrectly, but when checking out master, i cannot build the plugin, the error is 

```
go build -o packer-builder-linode
# github.com/dradtke/packer-builder-linode/linode
../../go/src/github.com/dradtke/packer-builder-linode/linode/builder.go:36:61: undefined: packer.Cache
make: *** [build] Error 2
```

If i remove the reference to packer.Cache in the function signature, then it builds fine. However, potentially unrelated, the packer build completes but then it's unable to create the image -
`linode: Error creating image: [404] Not found`

Is there another branch I should be using?

Thanks

**Comment by displague** [comment]
@dave-lew99 This repo is in transit.  #9 will fix any build issues (once this project lives on github.com/linode )

**Comment by displague** [comment]
@dave-lew99 I think you should be able to work around the transitional issue with this:

```sh
eval $(go env)
git clone -b move-to-linode git@github.com:displague/packer-builder-linode.git $GOPATH/src/github.com/linode/packer-builder-linode
cd $GOPATH/src/github.com/linode/packer-builder-linode
make install
```

**Comment by dave-lew99** [comment]
@displague - same issue i'm afraid - don't worry, if it's work in progress I can wait.

**Comment by displague** [comment]
@dave-lew99 The project is in its new home.  Are you using go 1.11.5 or higher?

If you followed my previous steps, make sure to change the checked out branch back to master and pull.

**Comment by brannondorsey** [comment]
I can confirmed the `make install` build instructions work with `go version go1.12.1 darwin/amd64`.

**Comment by dave-lew99** [comment]
Ah - Go version - yes it builds fine now i've updated :)

I now have a weird issue where you can't create images if the source is linode/centos7 - this applies even if you've created an instance through the web console and manually try to take the image. I'll raise this with regular Linode support.

**Comment by displague** [comment]
Closing this since the build problems are resolved.

Thanks @dave-lew99 and @brannondorsey!

**Comment by kbinghamnetfoundry** [comment]
> Ah - Go version - yes it builds fine now i've updated :)
> 
> I now have a weird issue where you can't create images if the source is linode/centos7 - this applies even if you've created an instance through the web console and manually try to take the image. I'll raise this with regular Linode support.

Did you happen to find a solution there @dave-lew99 ? I appear to be facing the same issue.

**Comment by dave-lew99** [comment]
Hi @kbinghamnetfoundry yes i did - sorry - support informed me that there is a default limit of 2Gb per image with a total account limit of 10Gb. They were able to raise the per-image limit though.

I offered that i'd be happy to pay for more image storage (it appears to be free at the moment) as long as it was reasonable.
